FogosPT/fogosmobile

CONTRIBUTING.md
Added Redux Article to CONTRIbUTING.md
=> Update CONTRIBUTING.md to include Redux Article

lib/screens/components/fire_details.dart, lib/screens/home_page.dart, lib/screens/utils/widget_utils.dart, pubspec.yaml
Add Share functionality
Change the layout of the bottom sheet
Change the color of the icons in the bottom sheet to be the same as the fire
=> Fix for #4

lib/actions/preferences_actions.dart, lib/main.dart, lib/middleware/preferences_middleware.dart, lib/reducers/preferences_reducer.dart, lib/screens/assets/icons.dart, lib/screens/components/fire_details.dart, lib/screens/settings/fire_notifications.dart, lib/screens/settings/notifications.dart, lib/screens/settings/settings.dart, pubspec.lock
closes: #1 
Changed notification settings button to a drawer, to be possible to add the about page and other links in the future.
Settings screen now has the settings for notifications by location and the notifications for each fire the user has subscribed, and is possible to unsubscribe there.
=> Fire notification subscription

lib/screens/components/fire_details.dart
=> Change the share text

lib/main.dart
=> #13 change header colors when is in the app switcher

lib/main.dart, lib/middleware/preferences_middleware.dart, lib/middleware/shared_preferences_manager.dart
This PR will add the `SharedPreferencesManager` related to #10.
* `SharedPreferencesManager.init()` should be called on the app's startup.
* I ran the app on Android and everything seemed to be ok.
As a note, I've added some documentation to the public methods as well as the author/class header which is not present in the other classes from the project, so, because of that, feel free to remove/edit it.
=> #10 adds SharedPreferencesManager

lib/main.dart, lib/screens/components/fire_details.dart, lib/screens/home_page.dart, pubspec.lock, pubspec.yaml
Add ModalBarrier to display loading
Add loading to icon when setting notification status
Add loading to full screen when loading the map
When a bottom sheet is dismissed, the data is removed.
closes #11
=> Feature #11

lib/localization/fogos_localizations.dart, lib/main.dart, lib/screens/partners.dart
added textPartners to localizations *localizations commands not executed*;
added PARTNERS_ROUTE & Navigatior on Drawer;
added screens\partners.dart;
Closes #32
=> #32 Add Partnership page

ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, lib/localization/fogos_localizations.dart, lib/localization/generated/l10n/messages_en.dart, lib/localization/generated/l10n/messages_pt.dart, lib/main.dart, lib/screens/info_page.dart, pubspec.lock, pubspec.yaml
=> Information page PT version

lib/constants/endpoints.dart, lib/localization/fogos_localizations.dart, lib/main.dart, lib/screens/warnings.dart, pubspec.lock
=> #31 Add Warnings Screen

lib/main.dart, lib/screens/components/fire_gradient_app_bar.dart, lib/screens/settings/settings.dart, pubspec.lock
Implementation for a custom top application bar, so the mobile application follows the same application bar as the fogos.pt website.
closes #37
=> feature for issue - #37 (Style top application bar.)

lib/actions/fires_actions.dart, lib/constants/endpoints.dart, lib/constants/routes.dart, lib/main.dart, lib/middleware/fires_middleware.dart, lib/models/app_state.dart, lib/models/fire_details.dart, lib/models/statistics.dart, lib/reducers/app_reducer.dart, lib/reducers/fires_reducer.dart, lib/screens/components/details_history.dart, lib/screens/components/fireRisk.dart, lib/screens/components/fire_details.dart, lib/screens/components/meansStatistics.dart, lib/screens/fire_details.dart, lib/screens/home_page.dart, lib/screens/settings/fire_notifications.dart, lib/screens/settings/other_notifications.dart, lib/screens/utils/widget_utils.dart
Closes #2 
- ~~There will be situations where the timeline for the fires will be incorrect (fires with more than 24h), to fix this I suggest to change the way the labels are given from the API to be more consistent with dd/MM/yyyy H:mm, this problem will happen too on the Statistics Page~~
=> #2 Fire details page

ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, lib/main.dart, lib/screens/fire_details.dart, lib/screens/home_page.dart
=> Open fire details from notification

lib/reducers/app_reducer.dart, lib/screens/about/about.dart
closes #67
Reuses previous contributors list, and fixes a loading bug.
=> small bug fix on about page.

lib/screens/home_page.dart
=> #75 - Fixes map zoom exception by providing limits for both max and min zoom

lib/actions/fires_actions.dart, lib/main.dart, lib/middleware/preferences_middleware.dart, lib/models/app_state.dart, lib/models/fire.dart, lib/reducers/fires_reducer.dart, lib/screens/home_page.dart
Persists the filter options across sessions.
Requesting @miguelpruivo review, since he closed the issue for creating the filters.
=> persist filter option across sessions

lib/screens/components/warnings_list.dart, lib/screens/fire_list_page.dart, lib/screens/info_page.dart, lib/screens/settings/notifications.dart, lib/screens/statistics_page.dart
Relating to #84, this PR adds a `Scrollbar` to the `ListView` in the following screens:
- Fires list
- Warnings
- Madeira warnings
- Informations
- Stats
- Notifications
=> Adds scrollbar indicator to ListViews

android/app/build.gradle
=> Add check for gradle key properties file

lib/middleware/preferences_middleware.dart, lib/reducers/preferences_reducer.dart, lib/screens/home_page.dart
Fixes Satellite View
Refactors code
Please check if the behavior of the offline screen is still valid, I tried to refactor the code a bit
Offline View:
Satellite View:
=> #123 Fixes Satellite View

lib/localization/fogos_localizations.dart, lib/localization/generated/l10n/intl_messages_en.arb, lib/localization/generated/l10n/intl_messages_pt.arb, lib/localization/generated/l10n/messages_all.dart, lib/localization/generated/l10n/messages_en.dart, lib/localization/generated/l10n/messages_messages_pt.dart, lib/middleware/preferences_middleware.dart, lib/screens/settings/other_notifications.dart
Adds Plane Subscribe to "Others" View
=> FPG-110 Adds Planes Subscribe

lib/localization/fogos_localizations.dart, lib/localization/generated/l10n/intl_messages_pt.arb, lib/localization/generated/l10n/messages_all.dart, lib/localization/generated/l10n/messages_messages_pt.dart, lib/screens/info_page.dart
Please see if the changed strings are the correct ones or not
=> FPT-115 - Changes Strings

lib/actions/lightning_actions.dart, lib/constants/endpoints.dart, lib/main.dart, lib/middleware/lightnings_middleware.dart, lib/models/app_state.dart, lib/models/lightning.dart, lib/reducers/app_reducer.dart, lib/reducers/lightning_reducer.dart, lib/screens/home_page.dart, lib/store/app_store.dart, pubspec.lock, pubspec.yaml
- Adds lightning Endpoint
- Adds lightnings to the maps
Note: I added a todo for the onPressed. What happens when we click on a lightning?
=> FPT-109 Adds lightning

android/app/build.gradle
=> Bumps gradle version
